# -*- coding: utf-8 -*-
"""WineQuality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cMV6UWxRnLGBBa4_-ADhFqB0Jzfj4kT
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

data=pd.read_csv('/content/winequality-red.csv')

data.head()

X = data.drop(columns='quality', axis=1)
Y = data['quality'].apply(lambda y_value: 1 if y_value > 7 else 0)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1,stratify=Y)

model=RandomForestClassifier()
model.fit(X_train,Y_train)

a=[]
for i in range(0,11):
  a.append(input())

b=np.array(a)

br=b.reshape(1,-1)

model.predict(br)